development:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/github.com/as27/buffaloresourcetest/buffaloresourcetest_development.sqlite

test:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/github.com/as27/buffaloresourcetest/buffaloresourcetest_test.sqlite

production:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/github.com/as27/buffaloresourcetest/buffaloresourcetest_production.sqlite